apiVersion: v1
kind: Service
metadata:
  name: assign3-probe
  namespace: probe
  labels:
    app: assign3-probe
spec:
  ports:
  - port: 30000
    name: assign3-probe
    protocol: TCP
    targetPort: 8080
  selector:
    app: assign3-probe
  type: LoadBalancer