apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
        type: assign3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi