apiVersion: v1
kind: Service
metadata:
  name: assign3
  namespace: anamdari
  labels:
    app: assign3
spec:
  ports:
  - port: 30010
    name: assign3
    protocol: TCP
    targetPort: 8080
  selector:
    app: assign3
  type: LoadBalancer